config/routes.rb
Rails.application.routes.draw do
  resources :palettes
  resources :colours
  devise_for :users
  root 'pages#home'

end

app/models/color.rb
class Color < ActiveRecord::Base

	belongs_to :user
	has_many :palettes, :through => :palette_colours

end

app/models/colour.rb
class Colour < ActiveRecord::Base

	belongs_to :user
	has_many :palette_colours
	has_many :palettes, :through => :palette_colours

end

app/models/palette.rb
class Palette < ActiveRecord::Base

	belongs_to :user
	has_many :palette_colours
	has_many :colours, :through => :palette_colours

end

app/models/palette_colour.rb
class PaletteColour < ActiveRecord::Base

  belongs_to :colour
  belongs_to :palette
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :colours

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	def stored_location_for(resource)
		nil
	end

	def after_sign_in_path_for(resource)
		#path_to_redirect_to
		colours_path
	end


end

app/controllers/colours_controller.rb
class ColoursController < ApplicationController
  before_action :set_colour, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_user, only: [:edit, :update, :destroy]

  # GET /colours
  # GET /colours.json
  def index
    if params[:id]
      @colours = current_user.colours
    else 
      @colours = Colour.all
    end
  end

  # def user_index
  #   @user = current_user
  #   @colours = @user.colours
  # end

  # GET /colours/1
  # GET /colours/1.json
  def show
  end

  # GET /colours/new
  def new
    @colour = Colour.new
  end

  # GET /colours/1/edit
  def edit
  end

  # POST /colours
  # POST /colours.json
  def create
    @colour = Colour.new(colour_params)
    @colour.user_id = current_user.id

    respond_to do |format|
      if @colour.save
        format.html { redirect_to @colour, notice: 'Colour was successfully created.' }
        format.json { render :show, status: :created, location: @colour }
      else
        format.html { render :new }
        format.json { render json: @colour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colours/1
  # PATCH/PUT /colours/1.json
  def update
    respond_to do |format|
      if @colour.update(colour_params)
        format.html { redirect_to @colour, notice: 'Colour was successfully updated.' }
        format.json { render :show, status: :ok, location: @colour }
      else
        format.html { render :edit }
        format.json { render json: @colour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colours/1
  # DELETE /colours/1.json
  def destroy
    @colour.destroy
    respond_to do |format|
      format.html { redirect_to colours_url, notice: 'Colour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colour
      @colour = Colour.find(params[:id])
    end

    def set_user
      @colour = current_user.colours.find_by(id: params[:id])
      redirect_to colours_path, notice: "You can only updates colours created by your account." if @colour.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colour_params
      params.require(:colour).permit(:name, :hexcode)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/palettes_controller.rb
class PalettesController < ApplicationController
  before_action :set_palette, only: [:show, :edit, :update, :destroy]

  # GET /palettes
  # GET /palettes.json
  def index
    @palettes = Palette.all
  end

  # GET /palettes/1
  # GET /palettes/1.json
  def show
  end

  # GET /palettes/new
  def new
    @palette = Palette.new
  end

  # GET /palettes/1/edit
  def edit
  end

  # POST /palettes
  # POST /palettes.json
  def create
    @palette = Palette.new(palette_params)

    respond_to do |format|
      if @palette.save
        format.html { redirect_to @palette, notice: 'Palette was successfully created.' }
        format.json { render :show, status: :created, location: @palette }
      else
        format.html { render :new }
        format.json { render json: @palette.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /palettes/1
  # PATCH/PUT /palettes/1.json
  def update
    respond_to do |format|
      if @palette.update(palette_params)
        format.html { redirect_to @palette, notice: 'Palette was successfully updated.' }
        format.json { render :show, status: :ok, location: @palette }
      else
        format.html { render :edit }
        format.json { render json: @palette.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /palettes/1
  # DELETE /palettes/1.json
  def destroy
    @palette.destroy
    respond_to do |format|
      format.html { redirect_to palettes_url, notice: 'Palette was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_palette
      @palette = Palette.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def palette_params
      params.require(:palette).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error text-center">
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/palettes_helper.rb
module PalettesHelper
end

app/views/colors/_form.html.erb
<%= form_for(@color) do |f| %>
  <% if @color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul>
      <% @color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hexcode %><br>
    <%= f.text_field :hexcode, class: "spectrum minicolors-input" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colours/_form.html.erb
<%= form_for(@colour) do |f| %>
  <% if @colour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@colour.errors.count, "error") %> prohibited this colour from being saved:</h2>

      <ul>
      <% @colour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hexcode %><br>
    <%= f.text_field :hexcode, class: "spectrum minicolours-input" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colours/edit.html.erb
<% content_for :body_class, "edit-colour colour-adjust" %>
<% content_for :body_style, "background-colour: #{ @colour.hexcode }" %>

<div class="container">

	<h1>Edit colour</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @colour %> |
	<%= link_to 'Back', colours_path %>


	<% if @colour.user == current_user %>
		<%= link_to 'Destroy', @colour, method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
	
</div>

app/views/colours/index.html.erb
  <% if @colours.first %>

    <% @colours.each do |colour| %>
      <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6" style="background-color: <%= colour.hexcode %>;">
      	<div class="colour-section text-center">
        <!-- <h4 ><%= colour.name %></h4> -->
        <h3><%= colour.hexcode %></h3>
       <!--  <% if colour.user %>
          <p>By: <span class="email"><%= colour.user.try(:email) %></span></p>
        <% end %> -->

        <div class="links-container">
          <div class="copy-colour" data-colour="<%= colour.hexcode %>">
            Copy
          </div>

          <%= link_to 'Show', colour %>

          <% if colour.user == current_user %>
            <%= link_to 'Edit', edit_colour_path(colour) %>
          <% end %>
        </div>
      </div>


      </div>
    <% end %>

    <input type="text" name="clipboard">


  <% else %>
    <div class="container text-center no-colours">
      <p class="large serif">Uh oh!</p>
      <p class="large sans">It appears that you're living in a black &amp; white world.<br>Why not add a little colour by clicking the link below?</p>
      <!-- <a class="large serif" href=""> + Add A Colour. </a> -->
      <%= link_to '+ Add a Colour', new_colour_path, class: 'large serif' %>
    </div>
  <% end -%>

app/views/colours/new.html.erb
<% content_for :body_class, "add-colour colour-adjust" %>
<div class="text-center colour-container">
	
	<h1>Add New</h1>

	<%= render 'form' %>

	<%= link_to 'Back', colours_path %>

</div>

app/views/colours/show.html.erb
<% content_for :body_class, "show-colour" %>
<div class="container text-center edit-colour-holder" style="background-colour: <%= @colour.hexcode %>">
	
	<div class="jumbotron">
		<h2>
		  <%= @colour.name %>
		</h2>
	
		<h2 class="large">
		  <%= @colour.hexcode %>
		</h2>
	</div>

</div>


<div class="nav-subnav text-center">
	<% if @colour.user == current_user %>
		<%= link_to 'Edit', edit_colour_path(@colour) %>
	<% end %>
	<%= link_to 'Back', colours_path %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<ul class="nav navbar-nav navbar-left">
		<% if !current_page?(root_url) %>
			<li><%= link_to "Colour-Full", root_path, class: "navbar-brand" %></li>
		<% end -%>
		 
</li>
		</ul>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav navbar-left">
			<li class="dropdown">
				<a href="#" class="btn btn-default btn-bold dropdown-toggle" id="colorsMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
					Colours
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu" aria-labelledby="colorsMenu">
					<li><%= link_to "Explore", colours_path, class: "btn btn-default btn-bold" %></li>
					<% if user_signed_in? %>
							<li><%= link_to "My Colours", colours_path(id: current_user.id ), class: "btn btn-default btn-bold text-left" %></li>
							<li><%= link_to '+ New Colour', new_colour_path, class: "btn btn-default btn-bold text-left" %></li>
					<% end -%>
				</ul>
			</li>
			<li class="dropdown">
				<a href="#" class="btn btn-default btn-bold dropdown-toggle" id="palettesMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
					Palettes
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu" aria-labelledby="palettesMenu">
					<li><%= link_to "Explore", palettes_path, class: "btn btn-default btn-bold" %></li>
					<% if user_signed_in? %>
							<li><%= link_to "My Palettes", palettes_path(id: current_user.id ), class: "btn btn-default btn-bold text-left" %></li>
							<li><%= link_to '+ New Palette', new_palette_path, class: "btn btn-default btn-bold text-left" %></li>
					<% end -%>
				</ul>
			</li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
		<% if user_signed_in? %>
			<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
			<li><%= link_to "Settings", edit_user_registration_path %></li>
		<% else %>
			<li><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default" %></li>
			<li><%= link_to "Login", new_user_session_path, class: "btn btn-default" %></li>
		<% end %>
		</ul>
	</div><!-- /.navbar-collapse -->
	</div><!-- end of container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ColorFull</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '//use.typekit.net/ozc1cgj.js', 'data-turbolinks-track' => true %>
  <%= javascript_tag "try{Typekit.load({ async: true });}catch(e){}" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body class="<%= yield (:body_class) %>" style="<%= yield (:body_style) %>;">

	<%= render 'layouts/header' %>

		<% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info text-center") %>
    <% end -%>

		<%= yield %>

    
</body>
</html>

app/views/pages/home.html.erb
<% content_for :body_class, "home-page" %>

<div class="container">
	<div class="jumbotron text-center">
		<h1>Colour-Full</h1>
		<h5>A Palette App</h5>
	<!-- 	Click here to <%= link_to "Sign Up", "#", class: "btn btn-default" %>
	 -->
	 </div>

</div>

app/views/palettes/_form.html.erb
<%= form_for(@palette) do |f| %>
  <% if @palette.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@palette.errors.count, "error") %> prohibited this palette from being saved:</h2>

      <ul>
      <% @palette.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/palettes/edit.html.erb
<h1>Editing Palette</h1>

<%= render 'form' %>

<%= link_to 'Show', @palette %> |
<%= link_to 'Back', palettes_path %>

app/views/palettes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Palettes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @palettes.each do |palette| %>
      <tr>
        <td><%= palette.title %></td>
        <td><%= link_to 'Show', palette %></td>
        <td><%= link_to 'Edit', edit_palette_path(palette) %></td>
        <td><%= link_to 'Destroy', palette, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Palette', new_palette_path %>

app/views/palettes/new.html.erb
<% content_for :body_class, "add-color color-adjust" %>
<div class="text-center color-container">
	
	<h1>New Palette</h1>

	<%= render 'form' %>

	<%= link_to 'Back', palettes_path %>

</div>

app/views/palettes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @palette.title %>
</p>

<%= link_to 'Edit', edit_palette_path(@palette) %> |
<%= link_to 'Back', palettes_path %>